import numpy as np
import qutip as qt

def haar_random_state(N):
    """
    Generates a Haar random state. These are pure states uniformly distributed
    according to the Haar measure.
    """
    psi = qt.rand_ket(N)
    return psi * psi.dag()

def hilbert_schmidt_random_state(N):
    """
    Generates a Hilbert-Schmidt random mixed state.
    This corresponds to Tr_B(|psi><psi|) where |psi> is a Haar random bipartite
    pure state on a NxN system, or equivalently rho = G * G^dagger / Tr(...)
    where G is a complex Ginibre matrix.
    """
    G_mat = np.random.randn(N, N) + 1j * np.random.randn(N, N)
    G = qt.Qobj(G_mat)
    rho = G * G.dag()
    return rho / rho.tr()

def bures_random_state(N):
    """
    Generates a Bures random mixed state.
    According to the paper arxiv:1010.3570, this is generated by:
    rho = (I + U) * G * G^dagger * (I + U^dagger) / Tr(...)
    where G is a complex Ginibre matrix and U is a Haar random unitary.
    """
    G_mat = np.random.randn(N, N) + 1j * np.random.randn(N, N)
    G = qt.Qobj(G_mat)
    U = qt.rand_unitary(N)
    I = qt.qeye(N)
    
    rho = (I + U) * G * G.dag() * (I + U.dag())
    return rho / rho.tr()
