"""
test_random_states.py
=====================
Unit tests to mathematically verify the generation of Haar, 
Hilbert-Schmidt, and Bures random states via both Math and Circuit methods.
"""

import unittest
import numpy as np
import qutip as qt

# Import the math generators
from random_states import (
    haar_random_state, 
    hilbert_schmidt_random_state, 
    bures_random_state
)

# Import the circuit generators
from generator import generate_random_circuit

class TestRandomStateGenerators(unittest.TestCase):
    
    def verify_valid_density_matrix(self, rho, dim):
        """Helper function: Tests the universal rules of quantum mechanics."""
        self.assertTrue(rho.isoper, "State is not a density matrix operator.")
        self.assertEqual(rho.shape, (dim, dim), f"Matrix should be {dim}x{dim}.")
        
        # 1. Trace must be 1 (Conservation of Probability)
        self.assertAlmostEqual(rho.tr().real, 1.0, places=5, msg="Trace != 1")
        
        # 2. Must be Hermitian (rho == rho^dagger)
        diff = (rho - rho.dag()).norm()
        self.assertAlmostEqual(diff, 0.0, places=5, msg="Matrix is not Hermitian")
        
        # 3. Must be Positive Semi-Definite (No negative probabilities)
        for eig in rho.eigenenergies():
            self.assertGreaterEqual(eig.real, -1e-10, "Found negative eigenvalue")

    # ==========================================
    # 1. HAAR RANDOM STATES (Pure States)
    # ==========================================
    def test_math_haar_state(self):
        rho = haar_random_state(2)
        self.verify_valid_density_matrix(rho, 2)
        
        # Haar states are PURE. Purity must be exactly 1.0
        purity = (rho * rho).tr().real
        self.assertAlmostEqual(purity, 1.0, places=5, msg="Haar state is not pure!")

    def test_circuit_haar_state(self):
        # A deep random circuit applied to |0> creates a Haar pure state
        state = qt.basis(2, 0)
        ops, _, _ = generate_random_circuit(num_qubits=1, num_layers=50)
        
        for op in ops:
            state = op * state
            
        rho = state * state.dag() if state.isket else state
        self.verify_valid_density_matrix(rho, 2)
        
        purity = (rho * rho).tr().real
        self.assertAlmostEqual(purity, 1.0, places=5, msg="Circuit Haar state is not pure!")

    # ==========================================
    # 2. HILBERT-SCHMIDT STATES (Mixed States)
    # ==========================================
    def test_math_hilbert_schmidt_state(self):
        rho = hilbert_schmidt_random_state(2)
        self.verify_valid_density_matrix(rho, 2)
        
        # HS states are MIXED. Purity must be < 1.0 and >= 0.5 (for 1 qubit)
        purity = (rho * rho).tr().real
        self.assertLess(purity, 0.999, msg="HS state is not mixed!")
        self.assertGreaterEqual(purity, 0.499, msg="Purity fell below theoretical limit.")

    def test_circuit_hilbert_schmidt_state(self):
        # Circuit HS states require tracing out an entangled Environment
        total_qubits = 2 # 1 System + 1 Environment
        state = qt.tensor([qt.basis(2, 0)] * total_qubits)
        
        ops, _, _ = generate_random_circuit(total_qubits, num_layers=50)
        for op in ops:
            state = op * state
            
        # Trace out the environment (Qubit 1)
        rho = state.ptrace([0])
        self.verify_valid_density_matrix(rho, 2)
        
        purity = (rho * rho).tr().real
        self.assertLess(purity, 0.999, msg="Circuit HS state did not entangle with environment!")
        self.assertGreaterEqual(purity, 0.499)

    # ==========================================
    # 3. BURES STATES (Mixed States)
    # ==========================================
    def test_math_bures_state(self):
        rho = bures_random_state(2)
        self.verify_valid_density_matrix(rho, 2)
        
        # Bures states are MIXED, but biased heavily toward pure states.
        purity = (rho * rho).tr().real
        self.assertLess(purity, 0.999, msg="Bures state is not mixed!")
        self.assertGreaterEqual(purity, 0.499)
        
        # Note on Circuit Generation for Bures:
        # Bures states are not generated by simple random circuits. They require 
        # a specific mathematical construction: rho ~ (I + U) G G^dagger (I + U^dagger).
        # Therefore, we rely entirely on the math module to generate these!

if __name__ == '__main__':
    unittest.main(verbosity=2)